---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git
  namespace: ch-git
spec:
  type: Git
  pathname: https://github.com/philipwu08/testrepo
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mychannel
  namespace: ch-git
spec:
  type: Git
  pathname: https://github.com/rokej/testrepo.git
---
apiVersion: v1
kind: Namespace
metadata:
  name: git-sub-ns
---
apiVersion: v1
data:
  path: stable/ibm-mongodb-dev
kind: ConfigMap
metadata:
  name: ibm-mongodb-dev-cm
  namespace: git-sub-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: git-sub-ns
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-sub
  namespace: git-sub-ns
  annotations: 
    apps.open-cluster-management.io/cluster-admin: "true"
spec:
  channel: ch-git/git
  placement:
    placementRef: 
      name: towhichcluster
      kind: PlacementRule
