---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: v1
kind: Namespace
metadata:
  name: git-sub-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mychannel
  namespace: ch-git
spec:
  type: Git
  pathname: https://github.com/rokej/testrepo.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: second-level-sub
  namespace: git-sub-ns
  annotations:
    apps.open-cluster-management.io/github-path: day2
spec:
  channel: ch-git/mychannel
  placement:
    placementRef:
      name: dev-cluster
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-cluster
  namespace: git-sub-ns
spec:
  clusterSelector: {}
