apiVersion: v1
kind: Service
metadata:
  name: redis-master
  #  namespace: guestbook
  labels:
    app: acmapp
    tier: backend
    role: master
    app.kubernetes.io/part-of: git-sub-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master
