---
apiVersion: v1
kind: Namespace
metadata:
  name: git-sub-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: git-sub-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: git-sub-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
kind: Route
apiVersion: v1
metadata:
  name: frontend
  namespace: git-sub-ns
spec:
  host: www.example.com
  path: /
  to:
    kind: Service
    name: nginx
  port:
    targetPort: http
  wildcardPolicy: None
