---
apiVersion: v1
kind: Namespace
metadata:
  name: playback-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpm
  namespace: playback-ns
  labels:
    app: nginx-dpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dpm
  template:
    metadata:
      labels:
        app: nginx-dpm
    spec:
      containers:
      - name: nginx-dpm
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dpm
  namespace: playback-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    app: nginx-dpm
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-dpm
  type: LoadBalancer
---
kind: Route
apiVersion: v1
metadata:
  name: frontend
  namespace: playback-ns
  labels:
    app: acmapp
spec:
  host: www.example.com
  path: /
  to:
    kind: Service
    name: nginx-dpm
  port:
    targetPort: http
